### ISSUE TITLE
Не работает Purifier::clean($text);

### ISSUE THREAD

**Issue by isvk** [alexusmai/laravel-purifier#1]
Laravel 5.4.11
PHP 7.1x64

`use Alexusmai\LaravelPurifier\Purifier;`

**не работает:**
`Purifier::clean($text);`

**работает:**
`purifier($text);`
и
```
$purifier = new Purifier;
$purifier->clean($text);
```

**Comment by alexusmai** [comment]
`use Purifier;`

или без use

`\Purifier::clean($text);`

**Comment by isvk** [comment]
Спасибо!
