### ISSUE TITLE
Image Style Stripped Incorrectly

### ISSUE THREAD

**Issue by egknight** [alexusmai/laravel-purifier#5]
I am trying to clean but allow the style attribute..

Input
```
"<img class="img-fluid" src="/storage/uploads/abc.jpeg" alt="abc.jpeg" style="width: 25%;">\n"
```
Output

```
<p><img class="img-fluid" src="/storage/uploads/abc.jpeg" alt="abc.jpeg">\n
</p>
```

I've configured my settings as follows, including style within img[]
```

'HTML.Allowed'             => 'div,b,strong,i,em,u,a[href|title],ul,ol,li,p[style],br,span[style],img[width|height|alt|src|class|style]',
```
When I remove class from the img[] section it will strip class, but having style included still results in it being stripped.

I'm running PHP 7.1

Thanks

**Comment by alexusmai** [comment]
Hi, you can try use pixels, it's work.

`<img class="img-fluid" src="https://www.codeproject.com/KB/GDI-plus/ImageProcessing2/flip.jpg" alt="abc.jpeg" style="width:30px; height:30px;">`

[Demo](http://htmlpurifier.org/demo.php?filter%5BAutoFormat.AutoParagraph%5D=0&filter%5BAutoFormat.DisplayLinkURI%5D=0&filter%5BAutoFormat.Linkify%5D=0&filter%5BAutoFormat.RemoveEmpty%5D=0&filter%5BAutoFormat.RemoveSpansWithoutAttributes%5D=0&filter%5BNull_CSS.AllowedProperties%5D=1&filter%5BCore.CollectErrors%5D=0&filter%5BHTML.Allowed%5D=img%5Bwidth%7Cheight%7Calt%7Csrc%7Cclass%7Cstyle%5D&filter%5BNull_HTML.Doctype%5D=1&filter%5BHTML.SafeObject%5D=0&filter%5BHTML.TidyLevel%5D=medium&filter%5BURI.DisableExternalResources%5D=0&filter%5BNull_URI.Munge%5D=1&html=%3Cimg+class%3D%22img-fluid%22+src%3D%22https%3A%2F%2Fwww.codeproject.com%2FKB%2FGDI-plus%2FImageProcessing2%2Fflip.jpg%22+alt%3D%22abc.jpeg%22+style%3D%22width%3A30px%3B+height%3A30px%3B%22%3E&submit=Submit&experimental=1)

Why not working % - I don't know. You can ask this question on [HTMLPurifier Forum](http://htmlpurifier.org/phorum/)

**Comment by egknight** [comment]
That's not working sorry.

before

```
<img class="img-fluid" style="width: 396px; height: 297px;" src="/uploads/5a242b860a4c15a242b860a4d1.jpeg">
```

 after

```
<img class="img-fluid" src="/uploads/5a242b860a4c15a242b860a4d1.jpeg" alt="5a242b860a4c15a242b860a4d1.jpeg">
```

**Comment by egknight** [comment]
Including my purifier config

```
    'default'   =>  [
        'HTML.Doctype'                  => 'HTML 4.01 Strict',
        'HTML.Allowed'                  => 'div,b,strong,i,em,a[href|title],ul,ol,li,p[style],br,span[style],img[class|style|width|height|alt|src]',
        'CSS.AllowedProperties'         => 'font,font-size,font-weight,font-style,font-family,text-decoration,padding-left,color,background-color,text-align',
        'AutoFormat.AutoParagraph'      => true,
        'AutoFormat.RemoveEmpty'        => true,
    ],
```

**Comment by alexusmai** [comment]
Yes, you are right. If uses "HTML.Allowed" this not work.
I test now. But if use this configuration - it's work.

```
[
        'HTML.Doctype'                  => 'HTML 4.01 Strict',
        'HTML.Allowed'                  => 'div,b,strong,i,em,a[href|title],ul,ol,li,p[style],br,span[style],img[class|style|width|height|alt|src]',
        'AutoFormat.AutoParagraph'      => true,
        'AutoFormat.RemoveEmpty'        => true,
    ],
```
But as I said you can take more information on the official site. I'm not the developer of this package, I just wrote a helper for Laravel.

**Comment by egknight** [comment]
Thank you for solution, worked as expected.

I'll follow up with owner on %.

Thanks
